name: Deploy DAGs to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'orchestration/dags/**'
      - 'dags/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy DAGs to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "dags/*"
          target: "/home/ubuntu/airflow/dags"
          strip_components: 1
