name: Deploy Glue Jobs to S3

on:
  push:
    branches:
      - dev
    paths:
      - "spark/**"
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy Spark scripts and Libs to S3
        run: |
          # Sync Spark entry points
          aws s3 sync spark/ s3://pi-m4-datalake-maxi/scripts/ --exclude "*" --include "*.py"
          # Sync Modular Source Code (libs)
          aws s3 sync src/ s3://pi-m4-datalake-maxi/scripts/src/ --exclude "*" --include "*.py"
