name: Deploy Glue Jobs to S3

on:
  push:
    branches:
      - dev
    paths:
      - "spark/**"
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package and Copy Spark scripts to S3
        run: |
          # 1. Sync Spark entry points (Main jobs)
          aws s3 sync spark/ s3://pi-m4-datalake-maxi/scripts/ --exclude "*" --include "*.py"
          
          # 2. Package 'src' into a ZIP (Glue Requirement for --extra-py-files)
          zip -r src.zip src/
          
          # 3. Upload the packaged library
          aws s3 cp src.zip s3://pi-m4-datalake-maxi/scripts/lib/src.zip
